### ISSUE TITLE
support user-supplied types

### ISSUE THREAD

**Issue by tmc** [bxcodec/faker#1]

**Comment by bxcodec** [comment]
Can you provide some of explanation, please ? Some example, or something. 

Currently, `faker` only support for some native types, and a non Pointer of Struct type. 

For example : 

```go 
type Another struct {
   Other string 
}
type Something struct {
   Another
   SomeField int 
}
 type Sample struct {
  SampleID int 
  SomethingObj Something
}
```

**Comment by nochso** [comment]
How about an interface? Check for this interface when encountering structs and if it's implemented, call Fake.

```go
type Faker interface {
    // Fake your own struct.
    Fake() error
}
```
Mail addresses or phone numbers are good examples because they should look a certain way.
```go
type Mail string

func (m *Mail) Fake() error {
    m = "random@implementation.here"
    return nil
}
```

**Comment by bxcodec** [comment]
@nochso 
Cool.
I would appreciate for the pull request rather than a code snippet. Thanks

**Comment by bxcodec** [comment]
Add new function here #5 

Still need more example  of data that already has a fixed pattern. 
Maybe you could list more here LOL :D 
So we can add the function
