### ISSUE TITLE
dep ensure error

### ISSUE THREAD

**Issue by yonesko** [bxcodec/faker#107]
Trying to add your lib to project using [dep](https://github.com/golang/dep), but can't:
`
dep ensure -v --update github.com/bxcodec/faker

(4)         try github.com/bxcodec/faker@v3.4.0
(4)     ✗   "github.com/bxcodec/faker" imports "github.com/bxcodec/faker/v3/support/slice", which contains malformed code: no package exists at "github.com/bxcodec/faker/v3/support/slice"
`

**Comment by bxcodec** [comment]
Hi @yonesko,

Dep is no longer supported for this library since we're already moving to go modules since v3.
You can still able to use dep for any version before v3

**Comment by yonesko** [comment]
Thx, 
My project uses dep, what should I do now ?

**Comment by bxcodec** [comment]
I'm not sure, but I recommend you to upgrade your project to use go module because it's the official package manager from go

**Comment by bxcodec** [comment]
Also, if you see other libraries, it started to use the go module as the default package manager. So it's better to move to go module now
