### ISSUE TITLE
Usernames with non-alphabetical characters

### ISSUE THREAD

**Issue by tiramiseb** [bxcodec/faker#110]
Since v3.4.0 (specifically, feature "new lang tag"), the generated fake usernames may include non-alphabetical characters : "[", "\", "]", "^", "_" and "`" : those characters are in the ASCII table between lowercase and uppercase letters.

Before v3.4.0, it was based on the string `letterBytes`, which contained "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".

**Comment by bxcodec** [comment]
@musinit can you check on this, please?

**Comment by bxcodec** [comment]
Thanks for the issue @tiramiseb, will look on this by EOW. Either I or anyone who available will fix this.

**Comment by musinit** [comment]
Yes, I'll fix this

**Comment by musinit** [comment]
@bxcodec what do you think?
https://github.com/bxcodec/faker/pull/111

**Comment by tiramiseb** [comment]
for what it's worth, LGTM

**Comment by bxcodec** [comment]
fixed by #111
