### ISSUE TITLE
FakeData on interface that is a slice

### ISSUE THREAD

**Issue by pioz** [bxcodec/faker#116]
Is possible with faker do something like this:

```go
func BulkCreate(db *gorm.DB, records interface{}) {
	switch reflect.TypeOf(records).Kind() {
	case reflect.Slice:
		slice := reflect.ValueOf(records)
		for i := 0; i < slice.Len(); i++ {
			faker.FakeData(slice.Index(i).Interface())
			fmt.Println(slice.Index(i).Interface())
		}
		db.Create(slice.Interface())
	}
}
```

I've tried, but this function does not modify the `slice.Index(i).Interface()` with fake data.

Here a [playground](https://play.golang.org/p/YmVBqyb8IcS).

Any idea to achieve this behavior?

**Comment by bxcodec** [comment]
Hi, maybe you can try this.
https://play.golang.org/p/3MW4hrlE7vM

- I've changed the faker version, you're using the old one.
- I use reflect.Set to set the value back

I'm closing this issues, feel free to re-open if you have questions
