### ISSUE TITLE
nested pointer support

### ISSUE THREAD

**Issue by d4l3k** [bxcodec/faker#16]
It'd be really useful to have support for nested pointer structs and a probability for each pointer field whether or not it gets filled.

This would make it really easy to fuzz GRPC endpoints since you would be able to generate random messages.

**Comment by bxcodec** [comment]
Hello, I'm afraid that we can't do that. Maybe a bit impossible to do.

Because for Golang itself, the pointer's zero value is `nil`. So it will be impossible to generate data to nested pointer struct. 

```
package main

import (
	"fmt"
)

type Sample struct {
	ID int
}

type Example struct {
	sample *Sample
	Name   string
}

type Contoh struct {
	sample Sample
	Name   string
}

func main() {
	fmt.Println("Hello, playground")

	a := Example{}

	fmt.Println(a.sample)    // this will print nil value
	fmt.Println(a.sample.ID) //this will throw panic nil pointer

	//Compare to non pointer struct
	b := Contoh{}
	fmt.Println(b.sample)
	fmt.Println(b.sample.ID) //this will print 0

}
```
[Playground](https://play.golang.org/p/Fa72FzGnVUn)

**Comment by d4l3k** [comment]
It really is possible. I ended up writing my own version of this library since I wanted to fuzz some GRPC endpoints.

Ex:
```go
t := reflect.TypeOf((*foo)(nil))
v := reflect.New(t.Elem())
v.Elem().Set(randType(t.Elem()))
```

Full example:
https://play.golang.org/p/VL_cHtfeTI2

Here's the full fuzzing code:

https://gist.github.com/d4l3k/be19b7d32aa4908c5500421af0a5fd79

**Comment by bxcodec** [comment]
Cool, I've make a PR for this feature. Thank you for helping. I just realized this way. 🙄
