### ISSUE TITLE
Are there any plans to include cli tool for this?

### ISSUE THREAD

**Issue by chhabraamit** [bxcodec/faker#21]

**Comment by chhabraamit** [comment]
For cases like:

- when one can't include new dependency in their projects because of some reasons (like company restrictions)
- for cases where one can create structs literals and update some of the fields' values.

**Comment by agoalofalife** [comment]
while in terms this is not provided
@bxcodec what do you think?

**Comment by bxcodec** [comment]
For that case, I can't still imagine, how cli tool will work.

As we know, faker will generate random object inline  code based on struct. 

But, I think it would be interesting to do, I would appreciate any PR for this issue. 

What do you think @agoalofalife ?

**Comment by agoalofalife** [comment]
@bxcodec  I agree

**Comment by chhabraamit** [comment]
Awesome. Let me take a stab at it this weekend.

**Comment by bxcodec** [comment]
I think will close this, this issue is stale to long. Besides, I still can't imagine how CLI tools will work with faker.

**Comment by arjunmahishi** [comment]
> I think will close this, this issue is stale to long. Besides, I still can't imagine how CLI tools will work with faker.

I have a use case for a CLI tool. I wanted to generate a json file with dummy data for a given struct. If I could do this via CLI instead of writing code on my own, that would be great. The command would look some thing like this:

```bash
faker -type "StructName" -o "out.json"
# or   
faker -type "StructName" -format="toml" -o "out.toml"  
```
