### ISSUE TITLE
Panic if struct field is a named type

### ISSUE THREAD

**Issue by ilackarms** [bxcodec/faker#25]
the following code will panic:

```go
type Foo string

type MyStruct struct {
	Foo Foo
}

func test() {
	s := MyStruct{}
	faker.FakeData(s)
}
```

with the error `  reflect.Set: value of type int32 is not assignable to type <pkgname>.Foo`

My suggestion is to add a type conversion in `faker.go`. I've tested it manually and (at least for my use case) this fixes the issue.

**Comment by bxcodec** [comment]
Cool, I've merged this for a while. Will investigate for other custom types
