### ISSUE TITLE
using in loop results in duplicate values

### ISSUE THREAD

**Issue by perryao** [bxcodec/faker#29]
I'm generating data in a loop, but since `randomElementFromSliceString` seeds on every invocation, the generated values aren't random. I'd think seeding in `init` would be good enough, and removing the seed from `randomElementFromSliceString` would allow random data to be generated in a loop.

**Comment by pc06548** [comment]
Faced the same issue. I put `time.Sleep(1*time.Second)` in the loop. As I need generated data to store in text file, this hack worked.

**Comment by bxcodec** [comment]
@perryao can you post a few lines of code on how to reproduce it??

**Comment by perryao** [comment]
Hi @bxcodec. Here's some sample code showing this issue:

```
package main

import (
	"fmt"

	"github.com/bxcodec/faker"
)

type Person struct {
	FirstName string `faker:"first_name_male"`
	LastName  string `faker:"last_name"`
}

func main() {
	for i := 0; i < 5; i++ {
		p := Person{}
		_ = faker.FakeData(&p)
		fmt.Printf("%+v\n", p)
	}
}
```

Here's the an example log from running this (it'll be different on each invocation):

```
{FirstName:Arthur LastName:Nolan}
{FirstName:Arthur LastName:Nolan}
{FirstName:Arthur LastName:Nolan}
{FirstName:Arthur LastName:Nolan}
{FirstName:Arthur LastName:Nolan}
```
