### ISSUE TITLE
How to ignore field?

### ISSUE THREAD

**Issue by ecojuntak** [bxcodec/faker#36]
How I can ignore to generate fake data for any field?
Here is my code
```
package main

import (
	"fmt"

	"github.com/bxcodec/faker"
)

type User struct {
	ID    uint64
	Name  string `faker:"name"`
	Email string `faker:"email"`
}

func main() {
	user := User{}
	err := faker.FakeData(&user)
	if err != nil {
		fmt.Println(err)
	}

	fmt.Println(user)
}

```

The result is
```
{29 Prof. Telly Howe fFyqOAE@ZTMVG.net}
```

The faker generate random ID. Can I Ignore so the id not generated?

**Comment by bxcodec** [comment]
Just add the skipping tag like json.

This issue already solved in #32.
If you encounter another issue related to this, you can reply this comment later
