### ISSUE TITLE
Generate only for non-default fields

### ISSUE THREAD

**Issue by BGarretson** [bxcodec/faker#42]
I like this for populating test data - but often I want to be in control of a couple of the structs property values, and then fake whatever's left (and not skipped). Is this possible? I guess what I'm asking for is a 'ifDefaultValueForTypeThenGenerate' kind of functionality

Also, it would be cool if there was a way for us to feed you a func name that you invoke to populate the field. Product-specific fake data that you cannot provide could be added thus.

**Comment by bxcodec** [comment]
Can you explain it with some example that you've made with faker?? 

And btw, faker also support for a custom faker provider  at  #33

**Comment by sebastian-walter** [comment]
@BGarretson Yesterday my PR got merged which enables you to use the `keep` tag. When the tag is set the behaviour is the following:
* If the value differs from the zero value, faker will not change it
* If the value equals the zero value for this type, faker will set the value for you

**Comment by bxcodec** [comment]
closing for not-active thread
