### ISSUE TITLE
Support for less than tags with numbers and length of strings

### ISSUE THREAD

**Issue by umeat** [bxcodec/faker#49]
For context, I'm storing non standard uint and int lengths (for example uint2 and int12 as uint8 and int16). This data is being Deserialized from and Serialized to binary. if I use faker to make the struct, it may make a much larger value than will actually be Serialized to binary. So when I Deserialize that binary it does not equal the object that faker generated. Same issue with the length of strings.

My suggestion would be to implement a tag which lets you specify bounds for numbers, and lengths for strings.

**Comment by bxcodec** [comment]
Cool, I think this feature will very useful, but I'm not sure I can help to create it ASAP. But, I will appreciate any PR for this issue
