### ISSUE TITLE
Cannotn find package

### ISSUE THREAD

**Issue by andresprogra** [bxcodec/faker#62]
package github.com/bxcodec/faker/v3/support/slice: cannot find package "github.com/bxcodec/faker/v3/support/slice" in any of:
	/usr/local/go/src/github.com/bxcodec/faker/v3/support/slice (from $GOROOT)
	/home/andres/go/src/github.com/bxcodec/faker/v3/support/slice (from $GOPATH)

**Comment by bxcodec** [comment]
Hi @andresprogra 

Thanks for the issue,
This issue happens because you're not using the go module.
If you use godep, or any other dependency management, use the v2 tag
