### ISSUE TITLE
Skip does not really skip a struct

### ISSUE THREAD

**Issue by sebastian-walter** [bxcodec/faker#66]
I have the following use case:

```
type MyStruct struct {
	Title          string          `faker:"word,keep"`
	MyOtherStruct []MyOtherStruct `faker:"-"`
}
```

When I fake the data, I would expect that the initial data of `MyOtherStruct` would be persistent. But in fact, it is being reset by faker.

**Comment by bxcodec** [comment]
Wow, thanks for the report, I never expect that 😱
I will try to debug and resolve this ASAP.
