### ISSUE TITLE
Unique modifier

### ISSUE THREAD

**Issue by System-Glitch** [bxcodec/faker#76]
I have a use-case where I need to generate some structs and one of the fields needs to be unique. As the library doesn't have a unique modifier, I implemented `UniqueFaker` wrapper which retries the generation if the value has already been generated before.

This feature could be integrated officially into the library and I think it could be a very useful one. That way, uniqueness wouldn't require a wrapper and wouldn't require to instantiate multiple fakers for a single dataset.

**Comment by bxcodec** [comment]
Cool... 

You can open PR for that.

**Comment by System-Glitch** [comment]
My solution is not practical and not very clean.
I checked the current implementation of the lib and such change would require significant changes to the lib's code base, and likely break backwards compatibility. 

I'd like to discuss the possibilities before opening a PR. You may not be ok with the proposed change.
I thought of two possibilities to implement it:
- Change to an interface-based design, meaning that we would need to create a faker object before faking. That would let us keep the generated values in memory and limit the changes the developers would need to do to upgrade to the new version.
- Add a `FakerContext` parameter to `FakeData` function. The `FakerContext` would be a struct holding the generated data for uniqueness. This would require more changes for the developer but less changes to the code base.

**Comment by bxcodec** [comment]
How about the second solution, but you create a new function that accepts the context. 

Let say: `FakeUniqueData`, and behind of it we use the same function that `FakeData` has.

We don't have too break the API for the old version. But, I don't know if this possible to do?? 🤔

**Comment by bxcodec** [comment]
The first solution also acceptable. As long as we make it not breakings the backward compatibility

**Comment by System-Glitch** [comment]
I thought about another easier solution: add a global slice of remembered unique values and a function to reset it. This solution wouldn't break backward compatibility and wouldn't require any change for developers to upgrade to the new version. I will try to implement that and open a PR.

**Comment by bxcodec** [comment]
resolved by #77
