### ISSUE TITLE
Idea: Support for custom types

### ISSUE THREAD

**Issue by bcatubig** [bxcodec/faker#87]
The Golang YAML library allows parsing custom types by implementing the `Unmarshaler` interface. This possibly could be a solution for supporting custom types.

See 
- https://godoc.org/gopkg.in/yaml.v2#Unmarshaler 
- https://www.ribice.ba/golang-yaml-string-map/

**Comment by bxcodec** [comment]
Hmm, have you tried this before? Would be great if we can do this? 
I'm quite confused, LOL. I see the blog post is telling about `map[string]` stuff, I don't see anything related to custom /alias type 🤔
