### ISSUE TITLE
Arrays or Slices of Public structs not supported when tag is `faker:"len=?"`

### ISSUE THREAD

**Issue by michaelairola** [bxcodec/faker#92]
Adding the tag `faker:"len=1"` on a slice of a Public struct returns the error "Unknown Type". Without tag, faker generates the slice perfectly fine.

**Comment by quii** [comment]
I get the same problem

**Comment by bxcodec** [comment]
Hey guys, I will look into this soon, so busy lately 🙏 

But if you have time, mind submitting the PR?

**Comment by michaelairola** [comment]
Hey @bxcodec thanks for responding! 

So when I look back at this issue, I think I was looking for the wrong feature. It looks like the "len" tag establishes a desired length for strings in the tagged field (the field types that are currently effected by this tag are string, []string, and map[string]string). 

I didn't realize this at the time of writing this issue. My desired result was to control the length of the array, and it looks like the "boundary" tag has that purpose. 

It is interesting to note that this throws the exact same error as the issue discussed currently, so I'll go ahead and try to put together a PR that will fix this error for the "boundary" tag. 

As a side question, are there any tags that establish a desired exact length for an array instead of a boundary? This would be a neat feature to have :)

**Comment by Icety** [comment]
I needed the feature and didn't see a pr, so added the tag.
`slice_len=5` should do the trick
